### ISSUE TITLE
Quicktile doesn't work if it's booted by an autostart script

### ISSUE THREAD

**Issue by jingweno** [ssokolow/quicktile#104]
I installed the [autostart script](https://github.com/ssokolow/quicktile/blob/master/quicktile.desktop) script to `/etc/xdg/autostart`. The quicktile process was started properly but no key bindings worked. If I run `quicktile -d` in a terminal, everything worked as expected. I'm wondering what I miss.

**Comment by ricardochimal** [comment]
@jingweno dunno if it'd help but mine is

```
[Desktop Entry]
Encoding=UTF-8
Version=0.9.4
Type=Application
Name=quicktile
Comment=quicktile
Exec=quicktile --daemonize
OnlyShowIn=XFCE;
StartupNotify=false
Terminal=false
Hidden=false
```

I have it in `$HOME/.config/autostart/`

**Comment by ssokolow** [comment]
That *is* strange because it's *supposed* to work from an autostart script. Have you tried modifying the autostart script to run something like a script containing `echo "it ran" > ~/test.log` to make sure it's actually getting launched?

I know I've had trouble with my KDE being picky about running or not running autostart scripts which are listed as enabled.

Beyond that, what distro are you on? I'll try to download a VM and see if I can replicate the problem.

**Comment by jingweno** [comment]
I figured it out. The issue was with the arrow keys binding. This is my config:

```
[general]
cfg_schema = 1
ColumnCount = 3
UseWorkarea = True
ModMask = <Ctrl><Alt>
MovementsWrap = True

[keys]
Left = left
Right = right
```

The key bindings work if I run `quicktile` in a terminal but it doesn't if it's started by autostart. My distro is Ubuntu 18.04.

**Comment by ssokolow** [comment]
Interesting. It uses `XBindKeys` to grab them directly from the X server, so it should be the other way around unless it's somehow getting launched in the period before you session start scripts spin up the X server or during a brief window when something else has an exclusive grab on those keys.

**Comment by ssokolow** [comment]
Sorry for going silent. I grabbed a VM, but I've been spending all my time on a crunch to see if I can get the GTK+ 3.x rewrite of QuickTile ready in time for Python 2.x to fall out of support at the end of the month.

**Comment by ssokolow** [comment]
If you'd like to try it, the GTK 3 rewrite is out for testing in [this branch](https://github.com/ssokolow/quicktile/tree/gtk3_port).

Just don't use the pip URL in the README because it's pointing toward the master branch so it won't require a fix-up commit when I merge the branch into master.

If you want to use the "pip from a URL" install method, substitute this command:

```sh
sudo pip3 install https://github.com/ssokolow/quicktile/archive/gtk3_port.zip
```

**Comment by ssokolow** [comment]
Could you try making the following change to your autostart script and telling me what the resulting log file says?

`Exec=sh -c 'quicktile --daemonize > ~/quicktile.log'`

**Comment by ssokolow** [comment]
Closing for lack of response after two months.

**Comment by tamipangadil** [comment]
> @jingweno dunno if it'd help but mine is
> 
> ```
> [Desktop Entry]
> Encoding=UTF-8
> Version=0.9.4
> Type=Application
> Name=quicktile
> Comment=quicktile
> Exec=quicktile --daemonize
> OnlyShowIn=XFCE;
> StartupNotify=false
> Terminal=false
> Hidden=false
> ```
> 
> I have it in `$HOME/.config/autostart/`

This works on my side. I just copied the text above and save it on `~/.config/autostart/quicktile.desktop`. And restarted my PC and it works as expected. Thanks @ricardochimal
