### ISSUE TITLE
Skipping the 1/2 width option

### ISSUE THREAD

**Issue by kalligator** [ssokolow/quicktile#123]
Is the a way of skipping the 1/2 width option when cycling through the left (KP_4) and right (KP_6) windowing options? I.e. leaving only the 1/3 & 2/3 in a 3 column config.

I would like to reserve that for the window manager in elementary OS only as it allows for dragging the common border between two windows, with each one growing/shrinking respectively as desired.

**Comment by ssokolow** [comment]
At the moment, you have to edit QuickTile's source because I've been struggling with life issues for years and that's prevented me from resolving bug #13. (At the moment, I'm trying a new approach which, I hope, will finally get me back on track and allow me time to give my hobby projects the attention they need.)

For now, you want to edit [line 166](https://github.com/ssokolow/quicktile/blob/ca8105dcdd08c26de0ce6b987958c15a88489de2/quicktile/layout.py#L166) in the `make_winsplit_positions` function in `layout.py` to change `edge_steps = (0.5,) + cycle_steps` to just `edge_steps = cycle_steps`.

**Comment by kalligator** [comment]
Sorry for reopening but I couldn't just leave it with a like reaction. 
I want to thank you for the fast and straight to the point reply, it worked great! 

As for the issues you mention, I hope everything goes well and remember that multitasking is a myth and your primary focus should be on important things first like health and family.

**Comment by ssokolow** [comment]
> Sorry for reopening but I couldn't just leave it with a like reaction.
I want to thank you for the fast and straight to the point reply, it worked great!

No worries, and you didn't reopen it so no problem. I have no problem continuing to talk as long as the bug status stays at closed.

> As for the issues you mention, I hope everything goes well and remember that multitasking is a myth and your primary focus should be on important things first like health and family.

Hopefully, it will. Over the last ten years, I was so into the mess and so burned out and demotivated by it that I didn't even think to research what exactly was going on inside my head. Now, I've got a better idea, so my new plans should hopefully allow me to dig myself out of the hole.
