### ISSUE TITLE
3 columns layout, but gap between left and center

### ISSUE THREAD

**Issue by sebhahn** [ssokolow/quicktile#135]
Just came across quicktile and tested it on Linux Mint 21.1 Cinnamon. My screen resolution is 3440x1440 and I'd like to create 3 columns with left, center and right. However, there seems to be a small gap between left and center. Can this be easily fixed?

![Screenshot from 2023-02-21 10-00-26](https://user-images.githubusercontent.com/5929935/220298191-deceeb9e-97a9-45cb-9fc5-9ff6b741f085.png)

**Comment by ssokolow** [comment]
Yeah. I noticed that on my system too and I think it's a rounding bug somewhere in the stage where it converts percentages into pixels.

QuickTile currently considers every window in isolation, which is why rounding errors can do that.

My life sort of fell apart during COVID and I'm currently trying to get myself back in order but I've been wanting to rework how QuickTile actually generates its grid for a *long* time and I'll hopefully get to that when I start working on it again.

(Ever since all the way back in 2011 with #10, I've wanted to redesign this part of QuickTile so that I can implement keybindings to grow/shrink columns. #24 will also be solved at the same time.)

The new design I want will instead define the entire grid and then slot windows into it, ensuring that every usable pixel belongs to *some* cell.

That said, when I do pick this back up, the first thing I'm going to be doing is finishing a rewrite that I was in the middle of when progress fell apart to fix a whole slew of these open issues related to configurability... primarily solving #13 (un-hardcode presets) and other related bugs by switching to a JSON configuration format.

Given that I'm very much against usability regressions, this was the state of the new "pieces of QuickTile on my garage floor" when COVID threw a psychological monkey-wrench into things:

![Screenshot_20230221_070544](https://user-images.githubusercontent.com/46915/220340665-4772b11c-f699-4c98-9cc1-5934985fd15e.png)

**Comment by sebhahn** [comment]
Thanks for your feedback! Hope you get back on track with all your stuff!

I was wondering if you could point me to the right function where this rounding bug might occur, so that I can play around myself in my fork.

I think the new grid/slot approach should make things easier also for predefined layouts/grids.

**Comment by ssokolow** [comment]
It should be something in the `GravityLayout` class, since that's what's responsible for converting percentages into absolute pixel dimensions.

I put a lot of work into making the API Documentation section of the manual high-quality, so I suggest you start at http://ssokolow.com/quicktile/apidocs/layout.html

**Comment by sebhahn** [comment]
thanks a lot! I'll play around with the code in this section.

**Comment by sebhahn** [comment]
Just in case you are interested, I'll made a dirty fix with an offset added to the fraction of the center: 0.33 * 3440 + 0.34 * 3440 + 0.33 * 3440 = 3440
see here: https://github.com/sebhahn/quicktile/blob/master/quicktile/layout.py#L163

I think it would be nice to have the number of columns not as fixed variable in the .cfg file but as an argument calling quicktile
