### ISSUE TITLE
Other window fraction sizes (namely fourths)

### ISSUE THREAD

**Issue by zamicol** [ssokolow/quicktile#34]
Right now quicktile's defaults for a window size are 1/3, 1/2, and 2/3.  

As screens grow larger, it would be nice if other fractions were also easily available and configurable by the user, like 1/4 or 1/5.  

If I perhaps overlooked this functionality, it would be nice to add this information to the README.

**Comment by ssokolow** [comment]
Just so you know, I've finally started to do the big re-architecting I've wanted to do all these years and, as a result, there's now a `ColumnCount` key in the config file.

More improvements are planned, but that should be a good start.

Be warned, however, that the installation process has changed because I split QuickTile into multiple files to get past a mental block. It's still simple and you have the same choices, but you'll want to re-read the relevant section of the `README`.
