### ISSUE TITLE
Add "monitor-switch-all" command

### ISSUE THREAD

**Issue by kbsali** [ssokolow/quicktile#37]
It would be nice to have a "monitor switch" command for all open windows. A typical use case would be when working on a laptop while travelling, then plug it in to an external monitor, if I want to move all the windows to the external monitor I have to do that for each window one by one.

**Comment by ssokolow** [comment]
Just because life has been such a mess that I haven't been able to work on this doesn't mean I think the idea has no merit.

I'm reopening this to use it as a TODO.

**Comment by kbsali** [comment]
:) ok, thanks! I did not want to offend you! ;)

**Comment by ssokolow** [comment]
*chuckle* I just tried implementing this naïvely and it even cycled the desktops around. Looks like I'll need an extra check or two.

**Comment by ssokolow** [comment]
OK, I've implemented `monitor-prev-all` and `monitor-next-all`.

They're not perfect, but they have the same flaw as `monitor-prev` and `monitor-next`, which I intend to fix as a separate bug.

(QuickTile just blindly moves them around, rather than adapting the window geometry to be relative to the shape of the new monitor.)
