### ISSUE TITLE
install.sh fails if not executed from parentdir

### ISSUE THREAD

**Issue by Baerbeisser** [ssokolow/quicktile#84]
For example, like this i get:
`sudo ./.quicktile/install.sh`
`* Running setup.py install`
`python2: can't open file 'setup.py': [Errno 2] No such file or directory`

My solution would be adding `cd $(dirname $0)` at the top of install.sh

**Comment by ssokolow** [comment]
Huh. Looks like I missed a project when I was retrofitting that. One of these days, I'll have to try to cook up some kind of lint to ensure all my projects meet base standards.

Speaking of which, you don't need to use `sudo`. If you run it unprivileged, it'll run `setup.py build` without elevated privileges and then re-run itself with `sudo` for you.

Also, I generally use `cd "$(dirname "$(readlink -f "$0")")"` since it's a good idea to be in the habit of resolving symlinks.
