### ISSUE TITLE
Add uninstall instructions

### ISSUE THREAD

**Issue by dipnlik** [ssokolow/quicktile#94]
I installed quicktile but noticed it doesn't fit my needs, so I want to uninstall it, but I don't know how to do it.  I think this information could be in the readme and/or the project's webpage.

**Comment by ssokolow** [comment]
Good point. I'm still climbing out of a backlog of TODOs, but I'll try to find room for it in the near future.

**Comment by dipnlik** [comment]
Whoops, I thought I mentioned my install method in the 1st message, sorry!  I used the 2nd method, without `pip` and with `install.sh`.

**Comment by ssokolow** [comment]
Ahh. That one requires a bit of extra work because `setup.py` without `pip` doesn't build a record of what's being installed. (It's analogous to `./configure && make && sudo make install`)

First, you need to remove the autostart entry that `install.sh` adds:

```sh
sudo rm /etc/xdg/autostart/quicktile.desktop
```

Second, it may have installed a launcher menu entry:

```sh
sudo rm /usr/local/share/applications/quicktile.desktop
```

Third, you need to clear out the QuickTile command itself (which even `pip uninstall` doesn't reliably remove for some reason):

```sh
sudo rm /usr/local/bin/quicktile
```

Finally, you need to remove the body of QuickTile from your Python packages folder. That should just be a folder and possibly a metadata file but, since the layout differs between normal and development installs, I can't just double-check my hard drive and give you exact paths.

This command should tell you what you need to delete:

```sh
find /usr/local/lib/python2.7 -iname 'quicktile*'
```

**Comment by dipnlik** [comment]
Perfect, thanks for such a detailed explanation–and sorry for my late response, I saw your message as it came but only today I was able to follow the procedure.
